def pages(request):
    modulePages = {
        'Registration': [
            'add_customers',
            'manage_customers',
            'add_vendor',
            'manage_vendor',
            'add_estate_agents',
            'manage_estate_agents',
            'add_product_types',
            'manage_product_types',
            'add_products',
            'manage_products',
            'add_taxes',
            'manage_taxes',
            'add_bank_accounts',
            'manage_bank_accounts',
            'add_assets',
            'manage_assets',
            'add_users',
            'manage_users',
            'add_expense_types',
            'manage_expense_types',
            'add_warehouses',
            'manage_warehouses'
            ],
        'customers': ['add_customers', 'manage_customers'],
        'vendor': ['add_vendor', 'manage_vendor'],
        'estateAgents': ['add_estate_agents', 'manage_estate_agents'],
        'producttypes': ['add_product_types', 'manage_product_types'],
        'products': ['add_products', 'manage_products'],
        'taxes': ['add_taxes', 'manage_taxes'],
        'bankacounts': ['add_bank_accounts', 'manage_bank_accounts'],
        'assets': ['add_assets', 'manage_assets'],
        'users': ['add_users', 'manage_users'],
        'expensetypes': ['add_expense_types', 'manage_expense_types'],
        'warehouse': ['add_warehouses', 'manage_warehouses'],
    }
    return {"modulesPages": modulePages}