def pages(request):
    Registration = {
        "all_registration_pages": [
            "add_customers",
            "manage_customers",
            "add_vendor",
            "manage_vendor",
            "add_estate_agents",
            "manage_estate_agents",
            "add_product_types",
            "manage_product_types",
            "add_products",
            "manage_products",
            "add_taxes",
            "manage_taxes",
            "add_bank_accounts",
            "manage_bank_accounts",
            "add_assets",
            "manage_assets",
            "add_users",
            "manage_users",
            "add_expense_types",
            "manage_expense_types",
            "add_warehouses",
            "manage_warehouses",
        ],
        "customers": ["add_customers", "manage_customers"],
        "vendor": ["add_vendor", "manage_vendor"],
        "estateAgents": ["add_estate_agents", "manage_estate_agents"],
        "producttypes": ["add_product_types", "manage_product_types"],
        "products": ["add_products", "manage_products"],
        "taxes": ["add_taxes", "manage_taxes"],
        "bankacounts": ["add_bank_accounts", "manage_bank_accounts"],
        "assets": ["add_assets", "manage_assets"],
        "users": ["add_users", "manage_users"],
        "expensetypes": ["add_expense_types", "manage_expense_types"],
        "warehouses": ["add_warehouses", "manage_warehouses"],
        "all_account_pages": [
            "add_bank_deposit_voucher",
            "add_debit_notes",
            "add_expense_voucher",
            "add_journal_voucher",
            "add_opening_voucher",
            "add_payment_voucher",
            "add_receipt_voucher",
            "chart_of_accounts",
            "manage_bank_deposit_voucher",
            "manage_debit_notes",
            "manage_expense_voucher",
            "manage_journal_voucher",
            "manage_opening_voucher",
            "manage_payment_voucher",
            "manage_receipt_voucher",
        ],
        "PaymentVouchers": ["manage_payment_voucher", "add_payment_voucher"],
        "ExpenseVouchers": ["add_expense_voucher", "manage_expense_voucher"],
        "ReceiptVouchers": ["add_receipt_voucher", "manage_receipt_voucher"],
        "OpeningVouchers": ["add_opening_voucher", "manage_opening_voucher"],
        "JournelVouchers": ["add_journal_voucher", "manage_journal_voucher"],
        "DebitNotes": ["add_debit_notes", "manage_debit_notes"],
        "BankDeposits": ["add_bank_deposit_voucher", "manage_bank_deposit_voucher"],
        "ChartOfAccounts": ["chart_of_accounts"],
    }
    return {"pages": Registration}
